import io
import os
import datetime
import math
import pandas as pd

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


# ------------------------------------------------------------------------------
# FONT REGISTRATION (Ensures native rendering of ₹ Rupee symbol without missing glyph boxes)
# ------------------------------------------------------------------------------
FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"

def register_fonts():
    global FONT_REGULAR, FONT_BOLD
    candidates = [
        ("C:/Windows/Fonts/segoeui.ttf", "C:/Windows/Fonts/segoeuib.ttf"),
        ("C:/Windows/Fonts/arial.ttf", "C:/Windows/Fonts/arialbd.ttf"),
        ("C:/Windows/Fonts/calibri.ttf", "C:/Windows/Fonts/calibrib.ttf"),
        ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf")
    ]
    for norm_path, bold_path in candidates:
        if os.path.exists(norm_path):
            try:
                pdfmetrics.registerFont(TTFont("SmartFont", norm_path))
                if os.path.exists(bold_path):
                    pdfmetrics.registerFont(TTFont("SmartFont-Bold", bold_path))
                else:
                    pdfmetrics.registerFont(TTFont("SmartFont-Bold", norm_path))
                FONT_REGULAR = "SmartFont"
                FONT_BOLD = "SmartFont-Bold"
                break
            except Exception:
                continue

register_fonts()


# ------------------------------------------------------------------------------
# TWO-PASS CANVAS FOR PAGE NUMBERS & GLOBAL FOOTER
# ------------------------------------------------------------------------------
class NumberedCanvas(canvas.Canvas):
    """Custom canvas for two-pass page numbering and global running header/footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont(FONT_REGULAR, 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running Header (Pages 2+)
        if self._pageNumber > 1:
            self.drawString(36, 812, "Smart Tourism AI — Travel Itinerary & Predictions Report")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, 804, 559, 804)

        # Footer (All Pages)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(559, 25, page_text)
        self.drawString(36, 25, "Generated by Smart Tourism AI • Plan smarter. Travel better.")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 35, 559, 35)
        self.restoreState()


# Streamlit cache wrapper fallback
try:
    import streamlit as st
    cache_data = st.cache_data
except Exception:
    def cache_data(*args, **kwargs):
        if len(args) == 1 and callable(args[0]) and not kwargs:
            return args[0]
        return lambda f: f


def fmt_currency(val) -> str:
    """Format numeric values as Indian Rupee string using 'Rs.' to ensure clean PDF rendering without black square glyph boxes."""
    try:
        amt = float(val)
        if math.isnan(amt):
            return "Rs. 0"
        if amt == int(amt):
            return f"Rs. {int(amt):,}"
        return f"Rs. {amt:,.2f}"
    except (ValueError, TypeError):
        return "Rs. 0"


def clean_pdf_data(obj):
    """Recursively converts any Unicode Rupee symbol (₹) to 'Rs.' and °C to 'deg C' across all fields."""
    if isinstance(obj, str):
        s = obj.replace("₹", "Rs. ").replace("°C", " deg C").replace("°", " deg ")
        return s
    elif isinstance(obj, dict):
        return {k: clean_pdf_data(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [clean_pdf_data(v) for v in obj]
    return obj


def generate_trip_pdf(res: dict) -> bytes:
    """
    Generates a professional PDF report matching the EXACT approved order & data requirements.
    """
    if not isinstance(res, dict):
        res = {}

    res = clean_pdf_data(res)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=45,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()

    # Define clean typography using registered Unicode font
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=FONT_BOLD,
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=3
    )

    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#0EA5E9"),
        spaceAfter=10
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName=FONT_BOLD,
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )

    sub_section_heading = ParagraphStyle(
        'SubSectionHeading',
        parent=styles['Normal'],
        fontName=FONT_BOLD,
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#0EA5E9"),
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155")
    )

    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor("#1E293B")
    )

    cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=cell_style,
        fontName=FONT_BOLD
    )

    header_cell = ParagraphStyle(
        'TableHeaderCell',
        parent=styles['Normal'],
        fontName=FONT_BOLD,
        fontSize=8.5,
        leading=11.5,
        textColor=colors.white
    )

    disclaimer_style = ParagraphStyle(
        'DisclaimerText',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#64748B")
    )

    elements = []

    # --------------------------------------------------------------------------
    # 1. SMART TOURISM AI HEADER
    # --------------------------------------------------------------------------
    elements.append(Paragraph("Smart Tourism AI", title_style))
    elements.append(Paragraph("AI-Powered Smart Trip Plan & Predictions Report", subtitle_style))
    gen_date = datetime.date.today().strftime('%B %d, %Y')
    elements.append(Paragraph(f"<b>Report Generation Date:</b> {gen_date}", body_style))
    elements.append(Spacer(1, 6))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0EA5E9"), spaceAfter=10))

    # --------------------------------------------------------------------------
    # 2. TRIP OVERVIEW
    # --------------------------------------------------------------------------
    elements.append(Paragraph("1. Trip Overview", section_heading))
    spots_list = res.get("selected_spots") or []
    if spots_list:
        spot_names_str = ", ".join([str(s.get("name", "Spot")) for s in spots_list if isinstance(s, dict)])
    else:
        primary_spot_dict = res.get("primary_spot") or {}
        spot_names_str = str(primary_spot_dict.get("name", "Not available"))

    start_str = str(res.get("travel_start") or "").strip()
    end_str = str(res.get("travel_end") or "").strip()

    # FIX 1: Calculate duration directly from travel_start and travel_end (inclusive dates)
    calc_duration_days = None
    if start_str and end_str:
        try:
            d_start = pd.to_datetime(start_str).date()
            d_end = pd.to_datetime(end_str).date()
            calc_duration_days = (d_end - d_start).days + 1
        except Exception:
            calc_duration_days = None

    if calc_duration_days is None or calc_duration_days <= 0:
        try:
            calc_duration_days = int(res.get("duration_days", 1))
        except Exception:
            calc_duration_days = 1

    duration_display = f"{calc_duration_days} Days"

    overview_data = [
        [Paragraph("Selected District", cell_bold), Paragraph(str(res.get("selected_district", "Not available")), cell_style)],
        [Paragraph("Selected Destinations", cell_bold), Paragraph(spot_names_str, cell_style)],
        [Paragraph("Start Date", cell_bold), Paragraph(start_str if start_str else "Not available", cell_style)],
        [Paragraph("End Date", cell_bold), Paragraph(end_str if end_str else "Not available", cell_style)],
        [Paragraph("Trip Duration", cell_bold), Paragraph(duration_display, cell_style)],
        [Paragraph("Number of Travelers", cell_bold), Paragraph(f"{res.get('num_travelers', 'N/A')} traveler(s)", cell_style)],
        [Paragraph("Transport Mode", cell_bold), Paragraph(str(res.get("transport_mode", "N/A")).title(), cell_style)],
        [Paragraph("Accommodation Tier", cell_bold), Paragraph(f"{res.get('acc_tier', 'N/A')} Stay", cell_style)],
        [Paragraph("Upcoming Festival", cell_bold), Paragraph(str(res.get("festival", "None")), cell_style)],
    ]

    t_overview = Table(overview_data, colWidths=[150, 373])
    t_overview.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 4.5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(t_overview)
    elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 3. DAY-BY-DAY TRIP WEATHER (Climate & Weather Forecast)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("2. Climate & Weather Forecast", section_heading))

    climate_summary = res.get("predicted_climate") or {}
    daily_records = res.get("daily_climate_forecast") or []

    # FIX 2: Generate exact date sequence from start_str to end_str (inclusive)
    date_list = []
    try:
        if start_str and end_str:
            d_start = pd.to_datetime(start_str).date()
            d_end = pd.to_datetime(end_str).date()
            date_list = [d.strftime("%Y-%m-%d") for d in pd.date_range(d_start, d_end)]
    except Exception:
        date_list = []

    if not date_list and isinstance(daily_records, list):
        date_list = [str(rec.get("date", rec.get("Date", ""))) for rec in daily_records if isinstance(rec, dict) and (rec.get("date") or rec.get("Date"))]

    if not date_list:
        date_list = [start_str] if start_str else ["Not available"]

    # Map daily_records by date string for reliable lookup
    daily_map = {}
    if isinstance(daily_records, list):
        for rec in daily_records:
            if isinstance(rec, dict):
                r_dt = str(rec.get("date", rec.get("Date", ""))).strip()
                if r_dt:
                    daily_map[r_dt] = rec

    itinerary_table_data = [
        [
            Paragraph("Day", header_cell),
            Paragraph("Date", header_cell),
            Paragraph("Weather Condition", header_cell),
            Paragraph("Max Temp", header_cell),
            Paragraph("Min Temp", header_cell),
            Paragraph("Rainfall", header_cell)
        ]
    ]

    for idx, d_str in enumerate(date_list, start=1):
        try:
            formatted_date = pd.to_datetime(d_str).strftime("%b %d, %Y")
        except Exception:
            formatted_date = d_str

        # Look up exact date forecast from daily_map or list
        rec = daily_map.get(d_str, {})
        if not rec and idx - 1 < len(daily_records) and isinstance(daily_records[idx - 1], dict):
            rec = daily_records[idx - 1]

        fallback_weather_cond = climate_summary.get("weather_condition", "Pleasant & Clear")

        if isinstance(rec, dict) and rec:
            w_cond = rec.get("Weather_Condition", rec.get("weather_condition"))
            t_max = rec.get("Temperature_Max_C", rec.get("temperature_max"))
            t_min = rec.get("Temperature_Min_C", rec.get("temperature_min"))
            rain = rec.get("Rainfall_mm", rec.get("rainfall_mm"))

            if t_max is None or (isinstance(t_max, float) and math.isnan(t_max)):
                t_max = climate_summary.get("temperature_max", 30.0)
            if t_min is None or (isinstance(t_min, float) and math.isnan(t_min)):
                t_min = climate_summary.get("temperature_min", 20.0)
            if rain is None or (isinstance(rain, float) and math.isnan(rain)):
                rain = climate_summary.get("rainfall_mm", 0.0)

            if not w_cond or str(w_cond).strip().lower() in ["not available", "none", "n/a", ""]:
                r_val = float(rain) if isinstance(rain, (int, float)) and not math.isnan(rain) else 0.0
                t_val = float(t_max) if isinstance(t_max, (int, float)) and not math.isnan(t_max) else 30.0
                if r_val > 25.0:
                    w_cond = "Heavy Rain Expected"
                elif r_val > 10.0:
                    w_cond = "Moderate Rain / Showers"
                elif r_val > 2.0:
                    w_cond = "Light Rain / Drizzle"
                elif t_val > 36.0:
                    w_cond = "Hot & Sunny"
                elif t_val > 32.0:
                    w_cond = "Warm & Clear"
                else:
                    w_cond = fallback_weather_cond

            t_max_str = f"{float(t_max):.1f}°C" if isinstance(t_max, (int, float)) and not math.isnan(t_max) else "Not available"
            t_min_str = f"{float(t_min):.1f}°C" if isinstance(t_min, (int, float)) and not math.isnan(t_min) else "Not available"
            rain_str = f"{float(rain):.1f} mm" if isinstance(rain, (int, float)) and not math.isnan(rain) else "Not available"
        else:
            w_cond = fallback_weather_cond
            t_max_str = "Not available"
            t_min_str = "Not available"
            rain_str = "Not available"

        itinerary_table_data.append([
            Paragraph(f"Day {idx}", cell_bold),
            Paragraph(formatted_date, cell_style),
            Paragraph(str(w_cond), cell_style),
            Paragraph(t_max_str, cell_style),
            Paragraph(t_min_str, cell_style),
            Paragraph(rain_str, cell_style)
        ])

    t_itinerary = Table(itinerary_table_data, colWidths=[50, 95, 178, 65, 65, 70], repeatRows=1)
    t_itinerary.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    elements.append(t_itinerary)
    elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 4. CROWD LEVEL
    # --------------------------------------------------------------------------
    elements.append(Paragraph("3. Crowd Level", section_heading))
    crowd_results = res.get("crowd_results", [])
    if crowd_results:
        crowd_table_data = [
            [Paragraph("Destination Spot", header_cell), Paragraph("Category", header_cell), Paragraph("Crowd Level", header_cell)]
        ]
        for cr in crowd_results:
            c_level = str(cr.get("crowd_level", "N/A")).replace("🟢 ", "").replace("🟡 ", "").replace("🔴 ", "").strip()
            crowd_disp = c_level if c_level else "N/A"

            crowd_table_data.append([
                Paragraph(str(cr.get("spot_name", "N/A")), cell_bold),
                Paragraph(str(cr.get("category", "N/A")).title(), cell_style),
                Paragraph(crowd_disp, cell_style)
            ])
        t_crowd = Table(crowd_table_data, colWidths=[223, 140, 160], repeatRows=1)
        t_crowd.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E293B")),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('PADDING', (0, 0), (-1, -1), 4),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]))
        elements.append(t_crowd)
    else:
        elements.append(Paragraph("Not available", body_style))
    elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 5. ROUTE SUMMARY
    # --------------------------------------------------------------------------
    elements.append(Paragraph("4. Route Summary", section_heading))
    primary_spot_dict = res.get("primary_spot") or {}
    primary_spot_name = primary_spot_dict.get("name", "Destination")
    spots_sequence_str = " → ".join([str(s.get("name", "Spot")) for s in spots_list if isinstance(s, dict)]) if spots_list else str(primary_spot_name)

    # FIX 3: REMOVE duration_days * 35.0 fallback completely! Use only actual route_distance_km from res.
    route_dist_val = res.get("route_distance_km")
    if isinstance(route_dist_val, (int, float)) and not math.isnan(route_dist_val) and route_dist_val > 0:
        route_dist_disp = f"{float(route_dist_val):.1f} km"
    else:
        route_dist_disp = "Route distance unavailable"

    route_data = [
        [Paragraph("Travel Route Sequence", cell_bold), Paragraph(spots_sequence_str, cell_style)],
        [Paragraph("Estimated Route Distance", cell_bold), Paragraph(route_dist_disp, cell_style)],
    ]
    t_route = Table(route_data, colWidths=[160, 363])
    t_route.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 4.5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(t_route)
    elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 6. NEARBY LOCATION DETAILS (NO COST, NO FAKE 4.5 RATING, NO FAKE 0.0 KM DISTANCE, NO ATM/PARKING AS HOSPITALS)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("5. Nearby Location Details", section_heading))
    nearby_dict = res.get("nearby_amenities") or {}

    # FIX 5: ONLY use actual hospitals data. Do NOT convert ATMs or parking into hospitals!
    hotels_list = nearby_dict.get("hotels", []) if isinstance(nearby_dict, dict) else []
    restaurants_list = nearby_dict.get("restaurants", []) if isinstance(nearby_dict, dict) else []
    hospitals_list = nearby_dict.get("hospitals", []) if isinstance(nearby_dict, dict) else []

    has_nearby = False

    def build_nearby_table(items_list, cat_label):
        rows = [[
            Paragraph("Location Name", header_cell),
            Paragraph("Tier / Type", header_cell),
            Paragraph("Rating", header_cell),
            Paragraph("Distance", header_cell)
        ]]
        for it in items_list[:4]:  # Top items per category
            if not isinstance(it, dict):
                continue
            name = str(it.get("name", "Facility")).strip()
            tier_val = str(it.get("tier", it.get("type", cat_label))).title()

            # FIX 4: Remove rating fallback to 4.5. Format rating cleanly without missing glyph unicode symbols
            rating_val = it.get("rating")
            if isinstance(rating_val, (int, float)) and not math.isnan(rating_val) and rating_val > 0:
                rating_str = f"{rating_val:.1f} / 5.0"
            else:
                rating_str = "Not available"

            # FIX 4: Remove distance fallback to 0.0 km. If missing -> "Not available"
            dist_val = it.get("distance_km")
            if isinstance(dist_val, (int, float)) and not math.isnan(dist_val) and dist_val >= 0:
                dist_str = f"{dist_val:.2f} km"
            else:
                dist_str = "Not available"

            rows.append([
                Paragraph(name, cell_bold),
                Paragraph(tier_val, cell_style),
                Paragraph(rating_str, cell_style),
                Paragraph(dist_str, cell_style)
            ])

        if len(rows) > 1:
            tbl = Table(rows, colWidths=[203, 140, 90, 90], repeatRows=1)
            tbl.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#334155")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ('PADDING', (0, 0), (-1, -1), 4),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ]))
            return tbl
        return None

    # Lodging / Hotels Subsection
    if hotels_list:
        t_hotels = build_nearby_table(hotels_list, "Lodging / Hotels")
        if t_hotels:
            has_nearby = True
            elements.append(Paragraph("Lodging / Hotels", sub_section_heading))
            elements.append(t_hotels)
            elements.append(Spacer(1, 6))

    # Dining Subsection
    if restaurants_list:
        t_dining = build_nearby_table(restaurants_list, "Dining")
        if t_dining:
            has_nearby = True
            elements.append(Paragraph("Dining", sub_section_heading))
            elements.append(t_dining)
            elements.append(Spacer(1, 6))

    # Hospitals & Services Subsection
    if hospitals_list:
        t_services = build_nearby_table(hospitals_list, "Hospitals & Services")
        if t_services:
            has_nearby = True
            elements.append(Paragraph("Hospitals & Services", sub_section_heading))
            elements.append(t_services)
            elements.append(Spacer(1, 6))

    if not has_nearby:
        elements.append(Paragraph("Not available", body_style))
        elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 7. BUDGET ESTIMATION — MUST BE LAST MAJOR INFORMATION SECTION
    # --------------------------------------------------------------------------
    budget_elements = []
    budget_elements.append(Paragraph("6. Budget Estimation", section_heading))

    budget_breakdown = res.get("budget_breakdown") or {}
    total_budget = res.get("estimated_budget", 0.0)
    per_person = res.get("per_person_cost", 0.0)

    b_data = [
        [Paragraph("Expense Category", header_cell), Paragraph("Estimated Cost", header_cell)],
        [Paragraph("Transport Cost", cell_style), Paragraph(fmt_currency(budget_breakdown.get('travel_cost', 0)), cell_style)],
        [Paragraph("Accommodation / Stay", cell_style), Paragraph(fmt_currency(budget_breakdown.get('stay_cost', 0)), cell_style)],
        [Paragraph("Food & Dining", cell_style), Paragraph(fmt_currency(budget_breakdown.get('food_cost', 0)), cell_style)],
        [Paragraph("Entry Tickets & Sightseeing", cell_style), Paragraph(fmt_currency(budget_breakdown.get('entry_fees', 0)), cell_style)],
        [Paragraph("Misc. / Tolls / Parking", cell_style), Paragraph(fmt_currency(budget_breakdown.get('tolls_and_parking', 0)), cell_style)],
        [Paragraph("Total Estimated Budget", cell_bold), Paragraph(fmt_currency(total_budget), cell_bold)],
        [Paragraph("Per Person Estimated Cost", cell_bold), Paragraph(fmt_currency(per_person), cell_bold)]
    ]

    t_budget = Table(b_data, colWidths=[300, 223])
    t_budget.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0EA5E9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0, 0), (-1, -1), 4.5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -3), [colors.white, colors.HexColor("#F8FAFC")]),
        ('BACKGROUND', (0, -2), (-1, -1), colors.HexColor("#E0F2FE")),
    ]))
    budget_elements.append(t_budget)
    budget_elements.append(Spacer(1, 14))

    # Keep Budget Estimation together as a unified flowable block
    elements.append(KeepTogether(budget_elements))

    # --------------------------------------------------------------------------
    # 8. AI DISCLAIMER
    # --------------------------------------------------------------------------
    disclaimer_elements = []
    disclaimer_elements.append(Paragraph("<b>AI Disclaimer</b>", cell_bold))
    disclaimer_elements.append(Spacer(1, 2))
    disclaimer_elements.append(Paragraph(
        "Predictions and estimates are AI-generated and are not guaranteed facts. "
        "Please independently verify all outputs before making travel, financial, or other decisions.",
        disclaimer_style
    ))
    disclaimer_elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 9. FINAL FOOTER
    # --------------------------------------------------------------------------
    disclaimer_elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1"), spaceAfter=8))
    disclaimer_elements.append(Paragraph("<b>Thank you for using Smart Travel AI</b>", cell_bold))
    disclaimer_elements.append(Paragraph("Plan smarter. Travel better.", body_style))

    elements.append(KeepTogether(disclaimer_elements))

    # Build PDF with two-pass canvas maker
    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
